/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Light': '浅色',
    'Unlock Lenses': '解锁透镜',
    'Accelerator': '加速器',
    'Accumulator': '累加器',
    'Activate laser': '激活激光',
    'Activate prism': '激活棱镜',
    'Amplification': '放大',
    'Amplifier': '放大器',
    'On': '打开',
    'Off': '关闭',
    'Calculating...': '正在计算...',
    'Cooler': '冷却器',
    'Copied!': '已复制到剪切板!',
    'Decelerate photon': '减速光子',
    'Decelerator': '减速器',
    'Decelerate the photon!': '减速光子！',
    'Equip a lens': '装备一个透镜',
    'Exciter': '励磁机',
    'The Beacon': '灯塔',
    'Unlock buy max': '解锁购买最大',
    'You can equip all three lenses at once': '您可以一次装备所有三个透镜',
    'Red and Blue and Green': '红色和蓝色和绿色',
    'Changelog': '更新日志',
    'Cancel deceleration!': '取消减速！',
    'Charger': '充电器',
    'Chromaticity': '色度',
    'Deactivate the laser!': '停用激光！',
    'Decelerate only when energy level is above: ': '仅在能量等级高于以下等级时才减速：',
    'Double base light gain': '基础光收益翻倍',
    'Double light gain': '光收益翻倍',
    'Double wave frequency': '双波频率',
    'Double-slit experiment': '双缝实验',
    'Duplicator': '复写器',
    'Extra base multipler to light based on current energy level': '基于当前能量等级的光的额外基数倍增器',
    'Emergency save recovery system': '紧急存档恢复系统',
    'Fractured ray': '射线破裂',
    'Fragments of color': '颜色碎片',
    'Hotkeys': '快捷键',
    'I broke the laser': '我弄坏了激光',
    'If error appears, please take a screenshot and send it to me.': '如果出现错误，请截屏并将其发送给我。',
    'Infinity': '无限',
    'Oscillation': '振荡',
    'Multiplier': '倍数',
    'Stablized': '稳定',
    'Dark': '深色',
    'No': '否',
    'Submit': '提交',
    'Yes': '是',
    'Stablizing': '稳定',
    'Catalyst': '催化剂',
    'Coolant stablization': '冷却液稳定',
    'Crank it up!': '加快速度！',
    'Deactivate the laser to equip a lens!\n': '停用激光以装备透镜！\n',
    'Equip': '装备',
    'Activate the prism!': '激活棱镜！',
    'Activating the prism will:': '激活棱镜将：',
    'Activation energy': '活化能',
    'Convert all your light into rainbow, rounded down': '把你所有的光变成彩虹，向下取整',
    'Prism': '棱镜',
    'Rainbow': '彩虹',
    'Upgrades': '升级',
    'Backup decelerator': '备用减速器',
    'Anti-prism': '反棱镜',
    'Backup laser': '备用激光',
    'Buy max': '购买最大',
    'Decay': '衰变',
    'Colored lens': '彩色透镜',
    'Deep amplification': '深度放大',
    'Enlightened': '变亮',
    'Fractured ray ': '射线破裂',
    'Growth': '生长',
    'Deactivate laser': '停用激光',
    'Destructive': '破坏性',
    'Dilation': '扩张',
    'Divergence': '差异',
    'Each unique completion of interference grants 1 node.': '每完成一次干扰就会获得1个节点。',
    'Enter interference': '输入干扰',
    'Enter interferences to gain node!': '输入干扰以获得节点！',
    'Loadout': '装载',
    'Exit interference': '退出干扰',
    'Fusion': '融合',
    'Requirement': '要求',
    'Overclock': '超频',
    'Mitosis': '有丝分裂',
    'Stability': '稳定性',
    'Supernova': '超新星',
    'Tachyon': '速子',
    'Reset everything that prism activation resets': '重置激活棱镜所重置的一切',
    'Recursion': '递归',
    'Respec all upgrades when you activate prism': '激活棱镜时检查所有升级',
    'Sawtooth': '锯齿',
    'Set the base light gain multi to x1e10': '将基础光增益倍数设置为x1e10',
    'Continue playing': '继续游戏',
    'Replay with x2 light bonus': '重玩开局2倍光加成',
    'Replay without bonus': '重玩无奖励',
    'Complete the interference!': '完成干扰！',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '10th oscillation upgrade boost x2 -> x2.75': '第十次振荡升级提升x2-> x2.75',
    'Red ': '红色 ',
    'Red 干扰': '红色干扰',
    'Lenses are 75% weaker': '透镜强度降低75％',
    'Laser is 50% weaker': '激光强度降低50％',
    'All base light gain multipliers from oscillation upgrades are disabled': '振荡升级的所有基本光增益倍数均被禁用',
    'and activate the prism under the conditions.': '并在条件下激活棱镜。',
    'Laser runs x3 slower, but blue lens is 25% stronger': '激光的运行速度慢了x3，但蓝色透镜却提高了25％',
    'Multiplier to light, decreases based on time in current activation': '基于当前激活的时间而减少的光的倍数',
    'Multiplier to light, increases based on time in current activation': '基于当前激活的时间而增加的光的倍数',
    'Multiplier to light, increases based on light': '基于光增加的光的倍数',
    'Multiplier to light, based on number of interference you are in': '基于您所受的干扰数量的光的倍数',
    'Multiplier to light based on total number of nodes': '基于节点总数的光的倍数',
    'Laser runs x3 faster, but red lens is 25% stronger': '激光的运行速度提高了x3，但红色透镜的强度提高了25％',
    'Laser runs x3 faster, but blue lens is 25% stronger': '激光的运行速度提高了x3，但蓝色透镜的强度提高了25％',
    'Gain more rainbow based on unspent rainbow': '根据未使用的彩虹获得更多的彩虹',
    'Enabled': '启用',
    'Absolute': '绝对',
    'Red lens is 50% stronger': '红色透镜效果提高50％',
    'Interference': '干扰',
    'Increase base light gain based on your rainbow': '根据您的彩虹增加基本光增益',
    'All lenses are 25% stronger': '所有镜片强度提高25％',
    'Darkness': '黑暗',
    "Red": "红色",
    'Convert all your lights into rainbow, if possible': '如果可能，将所有光转换为彩虹',
    'Convergence': '收敛性',
    'Constructive': '建设性',
    'Conclusion': '结论',
    'Completions': '完成次数',
    'Completed?': '已完成？',
    'Complete the game': '将游戏通关',
    'The stablization energy level is softcapped instead of hardcapped': '稳定能量等级采用软上限代替硬上限',
    'To complete an interference, reach the requirement': '完成一次干扰，达到要求',
    'Your unspent rainbow boost light gain': '您未使用的彩虹增强光增益',
    'Your unspent rainbow boost laser': '您未用过的彩虹增强激光',
    'You can activate prism automatically': '您可以自动激活棱镜',
    'Unlock Laser': '解锁激光',
    'Unlock autobuyer for oscillation upgrades': '解锁自动购买器以进行振荡升级',
    'Static multiplier to light': '光的静态倍数',
    'Static': '静态',
    'Shallow amplification': '轻度放大',
    'Resonance': '谐振',
    'Quick charge': '快速充电',
    'Multiplier to light, grows based on your light': '光的倍数，增长基于你的光',
    'Multiplier to light, decays based on your light': '光的倍数，衰减基于你的光',
    'Multiplier to light gain based on number of prism activations': '基于棱镜激活次数的光增益乘数',
    'Multiplier to base light based on number of prism activations': '基于棱镜激活次数的基础光倍数',
    'Laser charges and stablizes 80% faster': '激光充能和稳定速度快80%',
    'Keep laser after activating prism': '激活棱镜后保持激光状态',
    'Keep auto photon decelerate when activating prism': '激活棱镜时保持自动光子减速',
    'Unlocks after activating prism!': '激活棱镜后解锁！',
    'Dispersion': '分散',
    'Remove': '移除',
    'Achievement Unlocked!': '成就已解锁！',
    'The stablization energy level cap is 30% higher, but it takes x3 time to stablize the laser': '稳定的能量等级上限提高了30%，但需要3倍的时间来稳定激光',
    'The energy level of the laser when charged is 30% higher, but it overheats 40% faster': '充电时激光的能量等级提高30％，但过热变快40％',
    'The energy level of the laser is 25% higher, the laser overheats 50% slower and stablizes 2x faster': '激光的能量等级提高25%，激光过热减慢50%和稳定速度x2',
    'Overheat': '过热',
    'Deactivated': '已停用',
    'Charged': '已充满',
    'Game saved!': '游戏已保存!',
    'Charging': '充电中',
    'Activate the laser!': '激活激光！',
    'Once you are done, press \"hard reset\" button to reset the game.': '完成后，请按“硬重置”按钮以重置游戏。',
    'Photon deceleration is 30% more powerful': '光子减速功能提高30％',
    'Please also include your save file when you send the screenshot (as it can speed up the debugging process).': '发送屏幕截图时，请同时提供您的存档文件（因为这样可以加快调试过程）。',
    'Please press F12 and open the console to see if any error shows up.': '请按F12键并打开控制台以查看是否出现任何错误。',
    'Reduce overheat penalty from 50% to 10': '将过热损失从50％降低到10％',
    'x1.5 to base light gain': 'x1.5到基础光增益',
    'This cannot be undone!': '此操作将不能被撤消！',
    'Your current save will be overwritten!': '您当前的游戏进度将被覆盖！',
    'Laser is 10% more powerful': '激光功率提高10％',
    'Maximum': '最大',
    'Max all oscillation upgrades': '最大化所有振荡升级',
    'Complete an interference': '完成一次干扰',
    'You can export your game by pressing \"export\" button': '您可以通过按“导出”按钮来导出游戏存档',
    'Wipe all data': '清除所有数据',
    'Vibrator': '振子',
    'Unlock automation for photon deceleration': '解锁用于光子减速的自动化',
    'This shouldn\'t take longer than a few seconds...': '这应该不超过几秒钟...',
    'This appears because the loading took too long.': '这似乎是因为加载时间太长。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Currently: ": "当前: ",
    "Energy level: ": "能量等级: ",
    "Theme: ": "主题: ",
    "Auto: ": "自动: ",
    "Rainbow: ": "彩虹: ",
    "Reward: ": "奖励: ",
    "Light: ": "光: ",
    "Completed achievement: ": "已达成成就: ",
    "Increase base light gain by ": "增加基础光增益",
    "Laser status: ": "激光状态: ",
    "Let there be light!": "让它发光！",
    "Oscillation speed: ": "振荡速度:",
    "Photon deceleration: ": "光子减速:",
    "Photon stock market takeover": "光子股票收购",
    "Toggle laser: ": "切换激光：",
    "Light up the universe!": "照亮宇宙!",
    'Decelerate only when energy level is above:': '仅在能量等级高于以下等级时才减速：',
    "Move completed achievement to the bottom: ": "将完成的成就移到底部：",
    "Optical Amplification": "光学放大",
    "Pre-emission tampering": "预发射干扰",
    "Number of activations: ": "激活次数：",
    "Activate prism: ": "激活棱镜：",
    "Buy Max: ": "购买最大: ",
    "Entering/Exiting an interference will": "进入/退出干扰将",
    "Node: ": "节点: ",
    "Yellow": "黄色",
    "Green": "绿色",
    "Blue": "蓝色",
    'Spectral Rupture': '光谱破裂',
    "Raise total light gain to the power of ": "将总的光增益提高到 ",
    "Interference background effect: ": "干扰背景效果：",
    "Activate the prism at X Rainbow:": "在X彩虹处激活棱镜：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Big thanks to my friend for testing the game.": "非常感谢我的朋友帮忙测试游戏。",
    "You have reached the end of the game.": "你已经达到了游戏的终点。",
    "You can either continue playing, reset with a bonus or reset without bonus.": "你可以选择继续游戏，重置获得奖励或无奖励重置。",
    'Export': '导出',
    "Hard Reset": "硬复位",
    "Interference:": "干扰：",
    "(Completed!": "(已完成!",
    " to light gain": "光增益",
    "Light ==>": "光 ==>",
    "Reset all your oscillation upgrades, laser and lenses": "重置所有振荡升级，激光和透镜",
    "Please paste your save file here": "请在此处粘贴您的保存代码",
    "Reset all your oscillation upgrades (Except photon deceleration upgrade)": "重置所有振荡升级（光子减速升级除外）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^光\: ([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^x([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^\n(.+)The photon is releasing (.+) Light per second$/, '光子每秒释放 $2 光'],
    [/^Complete (.+) interferences$/, '完成 $1 干扰'],
    [/^Reach (.+) Rainbow$/, '达到 $1 彩虹'],
    [/^Reach (.+) rainbow$/, '达到 $1 彩虹'],
    [/^Reach (.+) Light$/, '达到 $1 光'],
    [/^([\d\.]+)e(\d+) Light$/, '$1e$2 光'],
    [/^Reach (.+) Light without ever activating laser in current prism reset$/, '无需在当前棱镜复位中激活激光即可达到 $1 光'],
    [/^Cost\: (.+) Light$/, '成本：$1 光'],
    [/^Cost\: (.+) Rainbow$/, '成本：$1 彩虹'],
    [/^Cost\: (.+) Node$/, '成本：$1 节点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);