/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Light': '浅色',
    'Unlock Lenses': '解锁镜头',
    'Accelerator': '加速器',
    'Accumulator': '累加器',
    'Activate laser': '激活激光',
    'Activate prism': '激活棱镜',
    'Amplification': '放大',
    'Amplifier': '放大器',
    'On': '打开',
    'Off': '关闭',
    'Calculating...': '正在计算...',
    'Cooler': '冷却器',
    'Copied!': '已复制!',
    'Decelerate photon': '减速光子',
    'Decelerator': '减速器',
    'Decelerate the photon!': '减速光子！',
    'Equip a lens': '装备一个镜头',
    'Exciter': '励磁机',
    'The Beacon': '灯塔',
    'Spectral Rupture': '光谱破裂',
    'Unlock buy max': '解锁购买最大',
    'You can equip all three lenses at once': '您可以一次装备所有三个镜头',
    'Red and Blue and Green': '红色和蓝色和绿色',
    'Changelog': '更新日志',
    'Cancel deceleration!': '取消减速！',
    'Charger': '充电器',
    'Chromaticity': '色度',
    'Deactivate the laser!': '停用激光！',
    'Decelerate only when energy level is above: ': '仅在能量等级高于以下等级时才减速：',
    'Double base light gain': '基础光线收益翻倍',
    'Double light gain': '光线收益翻倍',
    'Double wave frequency': '双波频率',
    'Double-slit experiment': '双缝实验',
    'Duplicator': '复写器',
    'Extra base multipler to light based on current energy level': '基于当前能量等级的光线的额外基数倍增器',
    'Emergency save recovery system': '紧急存档恢复系统',
    'Fractured ray': '射线破裂',
    'Fragments of color': '颜色碎片',
    'Hotkeys': '快捷键',
    'I broke the laser': '我弄坏了激光',
    'If error appears, please take a screenshot and send it to me.': '如果出现错误，请截屏并将其发送给我。',
    'Infinity': '无限',
    'Oscillation': '振荡',
    'Pre-emission tampering': '',
    'Multiplier': '倍数',
    'Stablized': '稳定',
    'Dark': '深色',
    'No': '否',
    'Submit': '提交',
    'Yes': '是',
    'Stablizing': '稳定',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Game saved!': '游戏已保存!',
    'Charging': '充电中',
    'Activate the laser!': '激活激光！',
    'Once you are done, press \"hard reset\" button to reset the game.': '完成后，请按“硬重置”按钮以重置游戏。',
    'Photon deceleration is 30% more powerful': '光子减速功能提高30％',
    'Please also include your save file when you send the screenshot (as it can speed up the debugging process).': '发送屏幕截图时，请同时提供您的存档文件（因为这样可以加快调试过程）。',
    'Please press F12 and open the console to see if any error shows up.': '请按F12键并打开控制台以查看是否出现任何错误。',
    'Reduce overheat penalty from 50% to 10': '将过热损失从50％降低到10％',
    'x1.5 to base light gain': 'x1.5到基础光线增益',
    'This cannot be undone!': '此操作将不能被撤消！',
    'Your current save will be overwritten!': '您当前的游戏进度将被覆盖！',
    'Laser is 10% more powerful': '激光功率提高10％',
    'Maximum': '最大',
    'Max all oscillation upgrades': '最大化所有振荡升级',
    'Complete an interference': '完成一次干扰',
    'You can export your game by pressing \"export\" button': '您可以通过按“导出”按钮来导出游戏存档',
    'Wipe all data': '清除所有数据',
    'Vibrator': '振子',
    'Unlock automation for photon deceleration': '解锁用于光子减速的自动化',
    'This shouldn\'t take longer than a few seconds...': '这应该不超过几秒钟...',
    'This appears because the loading took too long.': '这似乎是因为加载时间太长。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Currently: ": "当前: ",
    "Energy level: ": "能量等级: ",
    "Theme: ": "主题: ",
    "Auto: ": "自动: ",
    "Rainbow: ": "彩虹: ",
    "Reward: ": "奖励: ",
    "Light: ": "光线: ",
    "Completed achievement: ": "已达成成就: ",
    "Increase base light gain by ": "增加基础光增益",
    "Laser status: ": "激光状态: ",
    "Let there be light!": "让它发光！",
    "Oscillation speed: ": "振荡速度:",
    "Photon deceleration: ": "光子减速:",
    "Photon stock market takeover": "光子股票收购",
    "Toggle laser: ": "切换激光：",
    "Light up the universe!": "照亮宇宙!",
    'Decelerate only when energy level is above:': '仅在能量等级高于以下等级时才减速：',
    "Move completed achievement to the bottom: ": "将完成的成就移到底部：",
    "Optical Amplification": "光学放大",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Big thanks to my friend for testing the game.": "非常感谢我的朋友帮忙测试游戏。",
    "You have reached the end of the game.": "你已经达到了游戏的终点。",
    "You can either continue playing, reset with a bonus or reset without bonus.": "你可以选择继续游戏，重置获得奖励或无奖励重置。",
    'Export': '导出',
    "Hard Reset": "硬复位",
    "Interference:": "干扰：",
    "(Completed!": "(已完成!",
    " to light gain": "光线增益",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^光线\: ([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^x([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^\n(.+)The photon is releasing (.+) Light per second$/, '光子每秒释放 $2 光线'],
    [/^Complete (.+) interferences$/, '完成 $1 干扰'],
    [/^Reach (.+) Rainbow$/, '达到 $1 彩虹'],
    [/^Reach (.+) rainbow$/, '达到 $1 彩虹'],
    [/^Reach (.+) Light$/, '达到 $1 光线'],
    [/^Reach (.+) Light without ever activating laser in current prism reset$/, '无需在当前棱镜复位中激活激光即可达到 $1 光线'],
    [/^Cost\: (.+) Light$/, '成本：$1 光线'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);